# Generated by Django 3.0.3 on 2020-03-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_dp', models.ImageField(upload_to='media/')),
                ('profile_name', models.CharField(max_length=30)),
                ('profile_password', models.CharField(max_length=20)),
                ('profile_biography', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_caption', models.CharField(max_length=200)),
                ('image_comments', models.CharField(max_length=300)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.Profile')),
            ],
        ),
    ]
